services:
  - type: web
    name: canteen-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && cp ../model/canteen_prediction_model.joblib ./
    startCommand: gunicorn -c gunicorn_conf.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
